"""
P-A: Paul Guillaume × Ambroise Vollard
미술품 진위 판정 챗봇 — CLIP zero-shot 기반.

두 명의 가상 감정가가 각자 다른 관점의 프롬프트로 그림을 평가합니다.
- 폴 기욤: 20세기 초 유럽 화가의 시각 (모더니즘/원시주의)
- 앙브루아즈 볼라르: 갤러리 딜러의 시각 (시장성/캔버스 품질)
"""

import gradio as gr
from transformers import pipeline
from PIL import Image

# ─────────────────────────────────────────────────────────────
# CLIP 모델 (그림 인식이 자연스러움)
# ─────────────────────────────────────────────────────────────
CLIP_MODEL = "openai/clip-vit-base-patch32"

print(f"Loading CLIP model: {CLIP_MODEL} ...")
clip = pipeline("zero-shot-image-classification", model=CLIP_MODEL)


# ─────────────────────────────────────────────────────────────
# 두 감정가의 시각: 같은 그림을 다른 관점으로 평가
# ─────────────────────────────────────────────────────────────
GUILLAUME_LABELS = {
    "real": "an authentic oil painting by a 20th century European master artist",
    "fake": "an AI-generated digital artwork or computer-generated image",
}

VOLLARD_LABELS = {
    "real": "a museum-quality original painting on canvas with traditional brushwork",
    "fake": "a synthetic image generated by artificial intelligence or stable diffusion",
}


def judge(image, labels):
    """주어진 라벨 쌍으로 진품/가품 확률 계산"""
    candidates = [labels["real"], labels["fake"]]
    results = clip(image, candidate_labels=candidates)
    real_score = next(r["score"] for r in results if r["label"] == labels["real"])
    fake_score = next(r["score"] for r in results if r["label"] == labels["fake"])
    return real_score, fake_score


# ─────────────────────────────────────────────────────────────
# 판정: 둘 다 진품 우세면 와우, 둘 다 가품 우세면 가품 의심
# ─────────────────────────────────────────────────────────────
REAL_THRESHOLD = 0.5  # CLIP은 이진 분류라 단순 비교


def appraise(image):
    if image is None:
        return "이미지를 업로드해주세요.", "", ""

    if isinstance(image, str):
        image = Image.open(image).convert("RGB")
    else:
        image = image.convert("RGB")

    g_real, g_fake = judge(image, GUILLAUME_LABELS)
    v_real, v_fake = judge(image, VOLLARD_LABELS)

    g_says_real = g_real > g_fake
    v_says_real = v_real > v_fake

    if g_says_real and v_says_real:
        verdict = "🎉 **와우!** 폴 기욤과 앙브루아즈 볼라르 모두 진품 판정을 내렸습니다."
    elif not g_says_real and not v_says_real:
        verdict = "⚠️ **가품 의심이니 고려해보세요.** (두 감정가 모두 AI 생성/위작 의심)"
    else:
        verdict = "🤔 **의견이 갈립니다.** 추가 검토를 권합니다."

    g_status = "✅ 진품 판정" if g_says_real else "❌ 가품 의심"
    v_status = "✅ 진품 판정" if v_says_real else "❌ 가품 의심"

    g_detail = (
        f"### 🎩 폴 기욤\n"
        f"*시각: 20세기 초 유럽 화가*\n\n"
        f"- 판정: **{g_status}**\n"
        f"- 진품 확률: `{g_real:.1%}`\n"
        f"- AI/위작 확률: `{g_fake:.1%}`"
    )
    v_detail = (
        f"### 🎨 앙브루아즈 볼라르\n"
        f"*시각: 갤러리 딜러*\n\n"
        f"- 판정: **{v_status}**\n"
        f"- 진품 확률: `{v_real:.1%}`\n"
        f"- AI/위작 확률: `{v_fake:.1%}`"
    )

    return verdict, g_detail, v_detail


# ─────────────────────────────────────────────────────────────
# UI
# ─────────────────────────────────────────────────────────────
DESCRIPTION = """
# 🖼️ P-A : 폴 기욤 × 앙브루아즈 볼라르

> CLIP zero-shot 기반 미술품 진위 1차 판정 도구

20세기 초 파리에서 활동했던 두 명의 전설적인 미술상이
**서로 다른 관점**으로 작품을 평가합니다.

- 🎩 **폴 기욤** — 화가의 눈으로 본 진위 (붓터치, 모더니즘 시각)
- 🎨 **앙브루아즈 볼라르** — 딜러의 눈으로 본 진위 (시장성, 캔버스 품질)

**판정 결과:**
- ✅ 둘 다 진품 → 🎉 와우!
- ⚠️ 둘 다 가품 의심 → 추가 검토
- 🤔 의견 분분 → 인간 전문가 검토

> ⚠️ *본 서비스는 참고용 사전 판정 도구입니다. 정식 감정은 전문 기관에 의뢰하세요.*
"""

with gr.Blocks(title="P-A : 미술품 진위 판정", theme=gr.themes.Soft()) as demo:
    gr.Markdown(DESCRIPTION)

    with gr.Row():
        with gr.Column(scale=1):
            image_input = gr.Image(type="pil", label="🖼️ 미술품 이미지 업로드")
            submit = gr.Button("🔎 감정 시작", variant="primary")

        with gr.Column(scale=1):
            verdict_out = gr.Markdown(label="최종 판정")
            guillaume_out = gr.Markdown(label="폴 기욤")
            vollard_out = gr.Markdown(label="앙브루아즈 볼라르")

    submit.click(
        fn=appraise,
        inputs=image_input,
        outputs=[verdict_out, guillaume_out, vollard_out],
    )

    gr.Markdown(
        "---\n"
        f"Built with 🤗 Transformers · CLIP zero-shot · Model: `{CLIP_MODEL}`"
    )


if __name__ == "__main__":
    demo.launch(server_name="0.0.0.0", server_port=7860, show_api=False)
